class Vocabulario:
    def __init__(self):
        self.palabras = [
            "el", "la", "los", "las", "un", "una", "unos", "unas",
            "de", "del", "al", "en", "con", "por", "para", "sin",
            "que", "quien", "cual", "como", "donde", "cuando", "porque",
            "y", "o", "pero", "si", "no", "aunque", "mientras",
            "ser", "estar", "tener", "hacer", "poder", "decir", "ver",
            "ir", "saber", "querer", "llegar", "pasar", "dar", "buscar",
            "siendo", "estado", "tenido", "hecho", "visto", "ido",
            "era", "era", "fue", "fueron", "había", "habían",
            "sol", "luna", "noche", "día", "tiempo", "año", "vida", "muerte",
            "casa", "puerta", "ventana", "calle", "ciudad", "camino", "bosque", "montaña",
            "mar", "río", "playa", "agua", "fuego", "aire", "tierra",
            "hombre", "mujer", "niño", "niña", "amigo", "enemigo", "padre", "madre",
            "ojo", "mano", "cabeza", "corazón", "alma", "cuerpo", "voz", "silencio",
            "negro", "blanco", "rojo", "verde", "azul", "amarillo", "oscuro", "claro",
            "grande", "pequeño", "alto", "bajo", "largo", "corto", "nuevo", "viejo",
            "bueno", "malo", "hermoso", "terrible", "extraño", "misterioso", "sagrado",
            "caminar", "correr", "hablar", "escuchar", "mirar", "sentir", "soñar",
            "comenzar", "terminar", "continuar", "esperar", "buscar", "encontrar",
            "llorar", "reír", "morir", "vivir", "amar", "odiar", "temer",
            "el", "ella", "ellos", "ellas", "esto", "eso", "aquello",
            "aquí", "allí", "ahora", "antes", "después", "siempre", "nunca",
            "más", "menos", "mucho", "poco", "bastante", "casi", "sólo",
            "primer", "segundo", "último", "mismo", "otro", "cada",
            "todo", "todos", "toda", "todas", "algún", "ningún",
            "se", "le", "me", "te", "nos", "les", "lo", "la",
            "su", "mi", "tu", "nuestro", "vuestro", "propio",
            "aún", "ya", "todavía", "solo", "quizá", "tal vez", "ciertamente",
            "cielo", "infierno", "mundo", "universo", "existencia", "destino",
            "luz", "sombra", "esperanza", "dolor", "paz", "guerra", "verdad", "mentira",
            "escuchar", "observar", "pensar", "recordar", "olvidar", "entender",
            "lluvia", "viento", "tormenta", "nieve", "frío", "calor",
            "árbol", "flor", "fruto", "hoja", "rama", "semilla",
            "perro", "gato", "pájaro", "pez", "lobo", "oso", "serpiente",
            "libre", "cautivo", "fuerte", "débil", "sabio", "loco",
            "rey", "reina", "príncipe", "princesa", "soldado", "mago", "bruja",
            "viaje", "regreso", "salida", "entrada", "camino", "sendero", "ruta",
            "secreto", "misterio", "enigma", "pregunta", "respuesta", "solución",
            "escribir", "leer", "contar", "relatar", "describir", "imaginar",
            "trabajo", "descanso", "juego", "fiesta", "celebración", "tristeza", "alegría",
            "sangre", "agua", "polvo", "ceniza", "humo", "bruma", "neblina",
            "sube", "baja", "avanza", "retrocede", "gira", "cae", "levanta",
            "brilla", "arde", "fluye", "seca", "hunde", "flota",
            "tocar", "saborear", "oler", "percibir", "intuición", "razón",
            "ángel", "demonio", "espíritu", "fantasma", "sombra", "reflejo", "eco",
            "puente", "pared", "techo", "suelo", "fondo", "espacio", "lugar",
            "fin", "principio", "origen", "causa", "efecto", "consecuencia",
            "sueño", "pesadilla", "realidad", "ilusión", "verdad", "falsa",
            "cadena", "llave", "puerta", "cerradura", "secreto", "tesoro", "cofre",
            "rey", "esclavo", "amo", "siervo", "dueño", "posesión",
            "valiente", "cobarde", "honrado", "traidor", "leal", "temerario",
            "comprender", "aceptar", "rechazar", "elegir", "decidir", "actuar",
            "tiempo", "espacio", "movimiento", "cambio", "permanencia",
            "nacer", "crecer", "transformar", "morir", "renacer",
            "azul", "verde", "rojo", "negro", "blanco", "oro", "plata", "bronce",
            "feliz", "triste", "enojado", "asustado", "sorprendido", "calmado", "ansioso",
            "trabajo", "esfuerzo", "éxito", "fracaso", "victoria", "derrota",
            "familia", "comunidad", "humanidad", "naturaleza", "cosmos", "orden", "caos"
        ]
        self.palabras = list(set(self.palabras))
        self.ind2word = {i: w for i, w in enumerate(self.palabras)}
        self.word2ind = {w: i for i, w in enumerate(self.palabras)}
        self.pad_token = len(self.palabras)
        self.eos_token = len(self.palabras) + 1
        self.vocab_size = len(self.palabras) + 2