T = {
    "es": {
        "titulo": "Escritura Creativa con RL",
        "subtitulo": "Generador de textos con PPO + Lógica de Primer Orden",
        "consigna": "Consigna",
        "placeholder_consigna": "Escribe una consigna...",
        "genero": "Género",
        "tono": "Tono",
        "temperatura": "Temperatura",
        "generar": "Generar",
        "generando": "Generando...",
        "texto_generado": "Texto Generado",
        "feedback": "Feedback",
        "me_gusta": "Me gusta",
        "no_gusta": "No me gusta",
        "reentrenando": "Reentrenando modelo...",
        "config": "Configuración",
        "limpiar": "Limpiar",
        "feedback_negativo": "Feedback negativo guardado. El modelo aprenderá de esto.",
        "caption_ppo": "PPO — aprendizaje por refuerzo con retroalimentación del usuario.",
        "gracias_feedback": "¡Graces por tu feedback!",
        "sin_texto": "Genera un texto primero.",
        "ver_logs": "Ver logs de alineacion",
        "sin_logs": "No hay logs aún. Genera texto y da feedback.",
        "total_entradas": "Total de entradas",
        "idioma": "Idioma",
        "generos": ["Cuento", "Poema", "Guion"],
        "tonos": ["Misterioso", "Humorístico", "Dramático"],
        "modelo_cargado": "Modelo cargado",
        "idioma_cambiado": "Idioma cambiado a español",
    },
    "en": {
        "titulo": "Creative Writing with RL",
        "subtitulo": "Text generator with PPO + First-Order Logic",
        "consigna": "Prompt",
        "placeholder_consigna": "Write a prompt...",
        "genero": "Genre",
        "tono": "Tone",
        "temperatura": "Temperature",
        "generar": "Generate",
        "generando": "Generating...",
        "texto_generado": "Generated Text",
        "feedback": "Feedback",
        "me_gusta": "Like",
        "no_gusta": "Dislike",
        "reentrenando": "Retraining model...",
        "config": "Settings",
        "limpiar": "Clear",
        "feedback_negativo": "Negative feedback saved. The model will learn from this.",
        "caption_ppo": "PPO — reinforcement learning from user feedback.",
        "gracias_feedback": "Thanks for your feedback!",
        "sin_texto": "Generate a text first.",
        "ver_logs": "View alignment logs",
        "sin_logs": "No logs yet. Generate text and give feedback.",
        "total_entradas": "Total entries",
        "idioma": "Language",
        "generos": ["Tale", "Poem", "Script"],
        "tonos": ["Mysterious", "Humorous", "Dramatic"],
        "modelo_cargado": "Model loaded",
        "idioma_cambiado": "Language changed to English",
    },
}

def tr(key, lang="es"):
    return T.get(lang, T["es"]).get(key, T["es"].get(key, key))
